# Generated by Django 4.1 on 2022-08-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_manager_user_manager_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
