# Generated by Django 4.1 on 2022-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_dob_alter_employee_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
